language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: X3tGlUBSR0kGbyCnwzWFf6Ch2xO5jj++imKWY4tfl1QioNgtkKvjPlZbbXvdwT+1ppMei6OJB1W+qvDTxba52PvpHlsRXbAk0RI6RXhTBOCmXoYu7bTEgps6otSOVI92YulIlO7K/e/+h45cdnP/o/hhOXUa17wOuKVgUKmBAdmquphRWckj8hIUWeQyI5PL8R0ICz+t1a+9q/KEtUcopqsCkZWiXcT7zvVOCVXPbyyPv6UIPIExY6ejAkv8ODqLfKk6yCbuSWmqbKMRr59Lq8QLpeDnEgaOkPkeAI6DU/QGl+N6BcQyVHI2CgBUKH+UGy8P4OZ7IMANaIb8fSZUN0opQYnZ9TAaHmOqVVRe0PwqqBAqPuZxpuBKBVdoMkWTT+gPaIdVu7lw+qysE88H+Gf0Qq8z9b32JBKJaLNBoVHwLkvMZh20sTxsQqAnT/c1nGkZYHatJjyD+lqp3GE3ktmx1/Onk/vW/TQkCmZaaOQoU1/DljDM8X6yI3xQObS5r0EnjIfvm3twe4nIVbh4uJZ9vV5PU+yv5ElKXDbUqN8YxVdqNLGb84W3BIrdEtoyIiMXlmojF3ipUaDNhOSF0tHOw6G7D7ig0gPw/Hzy7681wrogbhtSpfHdHupq9j3yoHrfUNGEW+ccEABVuC7G0AsRawhYg9CiOUHLB99cSd0=
  on:
    tags: true
    repo: mCodingLLC/prime_sieve
    python: 3.9
